### ISSUE TITLE
Some issue with versioning

### ISSUE THREAD

**Issue by mcksp** [crystal-lang/html_builder#20]
Hi,
I believe there is some problem with versioning of this lib. Let's look at the `meta` tag, which was added to master, but version wasn't bumped and master is still on 0.2.1. There is also tag for version 0.2.2 without new updates from master, so without i.e. `meta` tag.

**Comment by straight-shoota** [comment]
The version in `shard.yml` on master is `0.2.2`. That should be correct.
I think the issue is just that there hasn't been a new release in a long time, so new features are not available in a release.
You can install the master version (or pin to a specific commit) and it should work. Or do you experience any issues with that?

**Comment by mcksp** [comment]
sorry, was looking `[version.cr](https://github.com/crystal-lang/html_builder/blob/master/src/html/builder/version.cr)` file, you are right. Didn't now i can pin to specific commit, otherwise everything good, thanks!

**Comment by straight-shoota** [comment]
Ah, `version.cr` is indeed wrong!
